# Generated by Django 4.2 on 2023-04-07 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Historia_Usuario",
            fields=[
                (
                    "cod_his_usu",
                    models.IntegerField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("titulo_his_usu", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "cod_usu",
                    models.IntegerField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("nombre_usu", models.CharField(max_length=20)),
                ("apellido_usu", models.CharField(max_length=20)),
                ("correo_usu", models.CharField(max_length=25)),
                ("clave_usu", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Version",
            fields=[
                ("nro_ver", models.IntegerField(auto_created=True)),
                (
                    "cod_ver",
                    models.IntegerField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("historia_ver", models.CharField(max_length=500)),
                (
                    "historia_usuario_ver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="historias_usuarios.historia_usuario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Proyecto",
            fields=[
                (
                    "cod_pro",
                    models.IntegerField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("nombre_pro", models.CharField(max_length=20)),
                ("descripcion_pro", models.CharField(max_length=200)),
                ("cantidad_pro", models.IntegerField(default=0)),
                (
                    "usuario_pro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="historias_usuarios.usuario",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="historia_usuario",
            name="proyecto_his_usu",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="historias_usuarios.proyecto",
            ),
        ),
    ]
