# Generated by Django 4.2 on 2023-04-06 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Historia_Usuario",
            fields=[
                (
                    "cod_his_usu",
                    models.IntegerField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("numero_his_usu", models.IntegerField(default=0)),
                ("titulo_his_usu", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "cod_usu",
                    models.IntegerField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("nombre_usu", models.CharField(max_length=20)),
                ("clave_usu", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Version",
            fields=[
                ("nro_ver", models.IntegerField(auto_created=True)),
                (
                    "cod_ver",
                    models.IntegerField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("role_ver", models.CharField(max_length=20)),
                ("objetivo_ver", models.CharField(max_length=20)),
                ("motivo_ver", models.CharField(max_length=40)),
                ("codiciones_ver", models.CharField(max_length=250)),
                (
                    "historia_usuario_ver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="historias.historia_usuario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Proyecto",
            fields=[
                (
                    "cod_pro",
                    models.IntegerField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("nombre_pro", models.CharField(max_length=20)),
                ("cantidad_pro", models.IntegerField(default=0)),
                (
                    "usuario_pro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="historias.usuario",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="historia_usuario",
            name="proyecto_his_usu",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="historias.usuario"
            ),
        ),
    ]
